import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { Alert, Box, Button, Card, CardContent, CircularProgress, Divider, MenuItem, Tab, Tabs, TextField, Typography } from '@mui/material';
import { Delete, Link as LinkIcon } from '@mui/icons-material';
import { getAlumnos } from '../../../api/alumnosApi';
import { getCursos } from '../../../api/cursosApi';
import { getDocentes } from '../../../api/docentesApi';
import { getMaterias } from '../../../api/materiasApi';
import { getTutores } from '../../../api/tutoresApi';
import { asignarAlumnoACurso, asociarTutorAAlumno, asignarDocenteMateriaCurso, desasignarAlumnoDeCurso, desasociarTutorDeAlumno, eliminarAsignacionDocenteMateriaCurso, getAsignacionesDocenteMateriaCurso, getCursosDeAlumno, getTutoresDeAlumno } from '../../../api/asignacionesApi';
import { extraerMensajeError } from '../../../utils/apiErrors';
import { Alumno, Curso, Docente, Materia, Tutor } from '../../../types';

export default function AsignacionesPage() {
  const [tab, setTab] = useState(0); const [alumnos, setAlumnos] = useState<Alumno[]>([]); const [cursos, setCursos] = useState<Curso[]>([]); const [docentes, setDocentes] = useState<Docente[]>([]); const [materias, setMaterias] = useState<Materia[]>([]); const [tutores, setTutores] = useState<Tutor[]>([]); const [error, setError] = useState(''); const [cargando, setCargando] = useState(true);
  useEffect(() => { Promise.all([getAlumnos(1,100), getCursos(1,100), getDocentes(1,100), getMaterias(1,100), getTutores(1,100)]).then(([a,c,d,m,t]) => { setAlumnos(a.datos); setCursos(c.datos); setDocentes(d.datos); setMaterias(m.datos); setTutores(t.datos); }).catch(err => setError(extraerMensajeError(err))).finally(() => setCargando(false)); }, []);
  if (cargando) return <Box sx={{ display:'flex', justifyContent:'center', py:8 }}><CircularProgress /></Box>;
  return <Box><Typography variant="h5" sx={{fontWeight:700}}>Asignaciones académicas</Typography><Typography variant="body2" color="text.secondary" sx={{mb:3}}>Administrá las relaciones académicas definidas por la API.</Typography>{error && <Alert severity="error" sx={{mb:2}} onClose={() => setError('')}>{error}</Alert>}<Card><Tabs value={tab} onChange={(_,v) => setTab(v)} variant="scrollable"><Tab label="Alumno ↔ Curso"/><Tab label="Alumno ↔ Tutor"/><Tab label="Docente ↔ Materia ↔ Curso"/></Tabs><Divider/><CardContent>{tab===0 && <AlumnoCurso alumnos={alumnos} cursos={cursos} error={setError}/>} {tab===1 && <AlumnoTutor alumnos={alumnos} tutores={tutores} error={setError}/>} {tab===2 && <DocenteMateriaCurso docentes={docentes} materias={materias} cursos={cursos} error={setError}/>}</CardContent></Card></Box>;
}

function AlumnoCurso({alumnos,cursos,error}:{alumnos:Alumno[];cursos:Curso[];error:(s:string)=>void}) { const [a,setA]=useState(''); const [c,setC]=useState(''); const [actuales,setActuales]=useState<number[]>([]); const cargar=async(id:number)=>{try{const r=await getCursosDeAlumno(id);setActuales(r.map(x=>Number(x.idCurso)).filter(Number.isFinite));}catch(e){error(extraerMensajeError(e));}}; const asignar=async()=>{if(!a||!c)return;try{await asignarAlumnoACurso(+a,+c);await cargar(+a);setC('');}catch(e){error(extraerMensajeError(e));}}; const quitar=async(id:number)=>{try{await desasignarAlumnoDeCurso(+a,id);await cargar(+a);}catch(e){error(extraerMensajeError(e));}}; return <Panel title="Asignar alumno a curso"><Select label="Alumno" value={a} setValue={v=>{setA(v);cargar(+v)}} options={alumnos.map(x=>({id:x.idAlumno,label:`${x.apellido}, ${x.nombre} — DNI ${x.dni}`}))}/><Select label="Curso" value={c} setValue={setC} disabled={!a} options={cursos.map(x=>({id:x.idCurso,label:`${x.grado}° "${x.division}" — ${x.anio}`}))}/><Button variant="contained" startIcon={<LinkIcon/>} onClick={asignar} disabled={!a||!c}>Asignar</Button><RelationList items={actuales.map(id=>({id,label:(()=>{const x=cursos.find(y=>y.idCurso===id);return x?`${x.grado}° "${x.division}" — ${x.anio}`:`Curso #${id}`})()}))} onDelete={quitar}/></Panel>; }

function AlumnoTutor({alumnos,tutores,error}:{alumnos:Alumno[];tutores:Tutor[];error:(s:string)=>void}) { const [a,setA]=useState('');const [t,setT]=useState('');const [p,setP]=useState('');const [r,setR]=useState(true);const [actuales,setActuales]=useState<{idTutor:number;parentesco?:string|null;esResponsablePrinc?:boolean}[]>([]);const cargar=async(id:number)=>{try{setActuales(await getTutoresDeAlumno(id));}catch(e){error(extraerMensajeError(e));}};const asignar=async()=>{if(!a||!t)return;try{await asociarTutorAAlumno(+a,{idTutor:+t,parentesco:p||undefined,esResponsablePrinc:r});await cargar(+a);setT('');setP('');}catch(e){error(extraerMensajeError(e));}};const quitar=async(id:number)=>{try{await desasociarTutorDeAlumno(+a,id);await cargar(+a);}catch(e){error(extraerMensajeError(e));}};return <Panel title="Asociar tutor a alumno"><Select label="Alumno" value={a} setValue={v=>{setA(v);cargar(+v)}} options={alumnos.map(x=>({id:x.idAlumno,label:`${x.apellido}, ${x.nombre}`}))}/><Select label="Tutor" value={t} setValue={setT} disabled={!a} options={tutores.map(x=>({id:x.idTutor,label:`${x.apellido}, ${x.nombre} — DNI ${x.dni}`}))}/><TextField label="Parentesco" value={p} onChange={e=>setP(e.target.value)} fullWidth/><TextField select label="Responsable principal" value={r?'si':'no'} onChange={e=>setR(e.target.value==='si')} fullWidth><MenuItem value="si">Sí</MenuItem><MenuItem value="no">No</MenuItem></TextField><Button variant="contained" startIcon={<LinkIcon/>} onClick={asignar} disabled={!a||!t}>Asociar</Button><RelationList items={actuales.map(x=>({id:x.idTutor,label:`${tutores.find(y=>y.idTutor===x.idTutor)?.apellido ?? `Tutor #${x.idTutor}`}${x.parentesco?` — ${x.parentesco}`:''}${x.esResponsablePrinc?' — Responsable':''}`}))} onDelete={quitar}/></Panel>; }

function DocenteMateriaCurso({docentes,materias,cursos,error}:{docentes:Docente[];materias:Materia[];cursos:Curso[];error:(s:string)=>void}) { const [d,setD]=useState('');const [m,setM]=useState('');const [c,setC]=useState('');const [actuales,setActuales]=useState<{id?:number;idDocente:number;idMateria:number;idCurso:number}[]>([]);const cargar=async(id:number)=>{try{const r=await getAsignacionesDocenteMateriaCurso(id);setActuales(r.map(x=>({id:x.idDocenteMateriaCurso,idDocente:+x.idDocente,idMateria:+x.idMateria,idCurso:+x.idCurso})));}catch(e){error(extraerMensajeError(e));}};const asignar=async()=>{if(!d||!m||!c)return;try{await asignarDocenteMateriaCurso({idDocente:+d,idMateria:+m,idCurso:+c});await cargar(+c);}catch(e){error(extraerMensajeError(e));}};const quitar=async(id:number)=>{if(!id)return;try{await eliminarAsignacionDocenteMateriaCurso(id);await cargar(+c);}catch(e){error(extraerMensajeError(e));}};return <Panel title="Asignar docente, materia y curso"><Select label="Curso" value={c} setValue={v=>{setC(v);cargar(+v)}} options={cursos.map(x=>({id:x.idCurso,label:`${x.grado}° "${x.division}" — ${x.anio}`}))}/><Select label="Docente" value={d} setValue={setD} options={docentes.map(x=>({id:x.idDocente,label:`${x.apellido}, ${x.nombre}`}))}/><Select label="Materia" value={m} setValue={setM} options={materias.map(x=>({id:x.idMateria,label:x.nombre}))}/><Button variant="contained" startIcon={<LinkIcon/>} onClick={asignar} disabled={!d||!m||!c}>Asignar</Button><RelationList items={actuales.map(x=>({id:x.id??0,label:`${docentes.find(y=>y.idDocente===x.idDocente)?.apellido ?? `Docente #${x.idDocente}`} — ${materias.find(y=>y.idMateria===x.idMateria)?.nombre ?? `Materia #${x.idMateria}`}`}))} onDelete={quitar}/></Panel>; }

function Select({label,value,setValue,options,disabled=false}:{label:string;value:string;setValue:(v:string)=>void;options:{id:number;label:string}[];disabled?:boolean}) { return <TextField select label={label} value={value} onChange={e=>setValue(e.target.value)} fullWidth disabled={disabled}>{options.map(x=><MenuItem key={x.id} value={x.id}>{x.label}</MenuItem>)}</TextField>; }
function Panel({title,children}:{title:string;children:ReactNode}) { return <Box sx={{display:'flex',flexDirection:'column',gap:2}}><Typography variant="h6">{title}</Typography>{children}</Box>; }
function RelationList({items,onDelete}:{items:{id:number;label:string}[];onDelete:(id:number)=>void}) { if(!items.length)return <Typography color="text.secondary">No hay relaciones registradas.</Typography>;return <Box sx={{display:'flex',flexDirection:'column',gap:1}}>{items.map(x=><Box key={`${x.id}-${x.label}`} sx={{display:'flex',justifyContent:'space-between',alignItems:'center',p:1.5,border:'1px solid',borderColor:'divider',borderRadius:2}}><Typography>{x.label}</Typography><Button color="error" size="small" startIcon={<Delete/>} onClick={()=>onDelete(x.id)}>Quitar</Button></Box>)}</Box>; }
